/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodGroupAffinityTermApplyConfiguration represents a declarative configuration of the PodGroupAffinityTerm type for use
// with apply.
type PodGroupAffinityTermApplyConfiguration struct {
	Weight            *int32                              `json:"weight,omitempty"`
	PodGroupSelector  *v1.LabelSelectorApplyConfiguration `json:"podGroupSelector,omitempty"`
	NamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
	TopologyTierName  *string                             `json:"topologyTierName,omitempty"`
	TopologyTier      *int32                              `json:"topologyTier,omitempty"`
}

// PodGroupAffinityTermApplyConfiguration constructs a declarative configuration of the PodGroupAffinityTerm type for use with
// apply.
func PodGroupAffinityTerm() *PodGroupAffinityTermApplyConfiguration {
	return &PodGroupAffinityTermApplyConfiguration{}
}

func (b *PodGroupAffinityTermApplyConfiguration) WithWeight(value int32) *PodGroupAffinityTermApplyConfiguration {
	b.Weight = &value
	return b
}

func (b *PodGroupAffinityTermApplyConfiguration) WithPodGroupSelector(value *v1.LabelSelectorApplyConfiguration) *PodGroupAffinityTermApplyConfiguration {
	b.PodGroupSelector = value
	return b
}

func (b *PodGroupAffinityTermApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *PodGroupAffinityTermApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

func (b *PodGroupAffinityTermApplyConfiguration) WithTopologyTierName(value string) *PodGroupAffinityTermApplyConfiguration {
	b.TopologyTierName = &value
	return b
}

func (b *PodGroupAffinityTermApplyConfiguration) WithTopologyTier(value int32) *PodGroupAffinityTermApplyConfiguration {
	b.TopologyTier = &value
	return b
}
